"""Deterministic rules resolution utilities."""

from .combatant import (
    Condition,
    CombatantSnapshot,
    DeathSaveResult,
    DurationType,
    SavingThrowResult,
    SUPPORTED_CONDITIONS,
    apply_damage,
    apply_healing,
    combatant_from_actor,
    combatant_from_monster_entry,
    is_dying,
    is_stable,
    roll_death_save,
    roll_saving_throw,
)
from .conditions import (
    RollMode,
    add_condition,
    attack_roll_mode,
    is_blocked_by_conditions,
    remove_condition,
    render_condition,
    target_grants_advantage,
    tick_condition_durations,
)
from .equipment import (
    derive_armor_class,
    equip_armor,
    equip_weapon,
    unequip_armor,
    unequip_weapon,
)
from .rest import (
    apply_long_rest,
    apply_short_rest,
)
from .reactions import (
    OppAttackResult,
    resolve_opportunity_attack,
    trigger_opportunity_attacks,
)
from .resolver import (
    ResolvedFeatureUse,
    ResolvedMonsterAttack,
    ResolvedSpellCast,
    ResolvedWeaponAttack,
    consume_spell_slot,
    resolve_feature_use,
    resolve_monster_action,
    resolve_spell_cast,
    resolve_weapon_attack,
)
from .levelling import (
    apply_xp_award,
    level_for_xp,
    xp_for_level,
    xp_reward_for_cr,
)
from .spell_effects import (
    AoeSpellResult,
    AoeTargetResult,
    begin_concentration,
    check_concentration,
    drop_concentration,
    resolve_aoe_spell,
)

__all__ = [
    "Condition",
    "CombatantSnapshot",
    "DurationType",
    "SUPPORTED_CONDITIONS",
    "apply_damage",
    "apply_healing",
    "combatant_from_actor",
    "combatant_from_monster_entry",
    "DeathSaveResult",
    "SavingThrowResult",
    "is_dying",
    "is_stable",
    "roll_death_save",
    "roll_saving_throw",
    "RollMode",
    "add_condition",
    "attack_roll_mode",
    "is_blocked_by_conditions",
    "remove_condition",
    "render_condition",
    "target_grants_advantage",
    "tick_condition_durations",
    "derive_armor_class",
    "equip_armor",
    "equip_weapon",
    "unequip_armor",
    "unequip_weapon",
    "apply_long_rest",
    "apply_short_rest",
    "OppAttackResult",
    "resolve_opportunity_attack",
    "trigger_opportunity_attacks",
    "ResolvedWeaponAttack",
    "ResolvedSpellCast",
    "ResolvedFeatureUse",
    "ResolvedMonsterAttack",
    "consume_spell_slot",
    "resolve_weapon_attack",
    "resolve_spell_cast",
    "resolve_feature_use",
    "resolve_monster_action",
    "apply_xp_award",
    "level_for_xp",
    "xp_for_level",
    "xp_reward_for_cr",
    "AoeSpellResult",
    "AoeTargetResult",
    "begin_concentration",
    "check_concentration",
    "drop_concentration",
    "resolve_aoe_spell",
]
